package brickbreaker.gui;


import brickbreaker.main.Game;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Frame;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLayer;
import javax.swing.SwingUtilities;

/**
 *
 * @author adam.sorrenti
 * @description
 * @date 
 */
public class MainGUI extends JFrame
{

    /**
     * Creates new form MainGUI
     */
   
    public int cStart = 1; //Count for first launch, intro, and info screens
    
    public int lastX, lastY;
    public static String imagePath = "Resources/Main ICO's/BreakerICO.png";//Path for ico

    public static BufferedImage myImg;
    public MainGUI()
    {          
            initComponents();   
    }
  public void levelUP(String level)
  {
      this.currentLevel.setText(level);//next level
  }
  public void levelName()
  {
        if(currentLevel.getText() == "1")
      {jLabel2.setText("Default Level!");}
      else
      {jLabel2.setText("Last Level!");}
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentLevel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        resetLevelP1 = new javax.swing.JPanel();
        levelBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        resetLevelP = new javax.swing.JPanel();
        cL = new javax.swing.JLabel();
        BB = new javax.swing.JLabel();
        By = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        minimizePanel = new javax.swing.JPanel();
        exitPanel = new javax.swing.JPanel();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BrickBreaker");
        setBackground(null);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(937, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        currentLevel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        currentLevel.setForeground(java.awt.Color.cyan);
        currentLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentLevel.setText("Lv");
        getContentPane().add(currentLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 180, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Restart");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 260, 40));

        resetLevelP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 20));

        javax.swing.GroupLayout resetLevelP1Layout = new javax.swing.GroupLayout(resetLevelP1);
        resetLevelP1.setLayout(resetLevelP1Layout);
        resetLevelP1Layout.setHorizontalGroup(
            resetLevelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        resetLevelP1Layout.setVerticalGroup(
            resetLevelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(resetLevelP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 260, 40));

        levelBar.setOpaque(false);
        levelBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                levelBarMouseDragged(evt);
            }
        });
        levelBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                levelBarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout levelBarLayout = new javax.swing.GroupLayout(levelBar);
        levelBar.setLayout(levelBarLayout);
        levelBarLayout.setHorizontalGroup(
            levelBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        levelBarLayout.setVerticalGroup(
            levelBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(levelBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Level Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 640, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Next Level");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 134, 110, 30));

        resetLevelP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 20));

        javax.swing.GroupLayout resetLevelPLayout = new javax.swing.GroupLayout(resetLevelP);
        resetLevelP.setLayout(resetLevelPLayout);
        resetLevelPLayout.setHorizontalGroup(
            resetLevelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        resetLevelPLayout.setVerticalGroup(
            resetLevelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(resetLevelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 120, 40));

        cL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cL.setForeground(new java.awt.Color(255, 255, 255));
        cL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cL.setText("Current Level:");
        getContentPane().add(cL, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 320, -1));

        BB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickbreaker/gui/Resources/title.png"))); // NOI18N
        getContentPane().add(BB, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 30, 340, -1));

        By.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        By.setForeground(new java.awt.Color(255, 255, 255));
        By.setText("By: Adam Sorrenti");
        getContentPane().add(By, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        jPanel2.setForeground(new java.awt.Color(255, 255, 51));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 500));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 30, 600, 500));

        minimizePanel.setMaximumSize(new java.awt.Dimension(30, 20));
        minimizePanel.setMinimumSize(new java.awt.Dimension(30, 20));
        minimizePanel.setOpaque(false);
        minimizePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizePanelMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizePanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout minimizePanelLayout = new javax.swing.GroupLayout(minimizePanel);
        minimizePanel.setLayout(minimizePanelLayout);
        minimizePanelLayout.setHorizontalGroup(
            minimizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        minimizePanelLayout.setVerticalGroup(
            minimizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(minimizePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 30, 30));

        exitPanel.setMaximumSize(new java.awt.Dimension(30, 20));
        exitPanel.setMinimumSize(new java.awt.Dimension(30, 20));
        exitPanel.setOpaque(false);
        exitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitPanelMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(exitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 30, 30));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickbreaker/gui/Resources/background.png"))); // NOI18N
        Bg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Bg.setMaximumSize(new java.awt.Dimension(937, 553));
        Bg.setMinimumSize(new java.awt.Dimension(937, 553));
        Bg.setPreferredSize(new java.awt.Dimension(937, 553));
        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 937, 553));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanelMouseEntered
        
        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickbreaker/gui/Resources/background_hover_min.png"))); // NOI18N
    }//GEN-LAST:event_minimizePanelMouseEntered

    private void minimizePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanelMouseExited

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickbreaker/gui/Resources/background.png"))); // NOI18N
    }//GEN-LAST:event_minimizePanelMouseExited

    private void exitPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseEntered

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickbreaker/gui/Resources/background_hover_x.png")));
    }//GEN-LAST:event_exitPanelMouseEntered

    private void exitPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseExited

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickbreaker/gui/Resources/background.png"))); // NOI18N
    }//GEN-LAST:event_exitPanelMouseExited

    private void exitPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseReleased

        System.exit(0);
    }//GEN-LAST:event_exitPanelMouseReleased

    private void minimizePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanelMouseReleased

        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizePanelMouseReleased

    private void levelBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelBarMousePressed
        lastX = evt.getXOnScreen();
        lastY = evt.getYOnScreen();
        
    }//GEN-LAST:event_levelBarMousePressed

    private void levelBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelBarMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        // Move frame by the mouse delta
        setLocation(getLocationOnScreen().x + x - lastX,
            getLocationOnScreen().y + y - lastY);
        lastX = x;
        lastY = y;

    }//GEN-LAST:event_levelBarMouseDragged
  public static void main(String[] args) {    
    SwingUtilities.invokeLater(new Runnable() {
        public void run() {
            new MainGUI();
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BB;
    private javax.swing.JLabel Bg;
    private javax.swing.JLabel By;
    private javax.swing.JLabel cL;
    private javax.swing.JLabel currentLevel;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel levelBar;
    private javax.swing.JPanel minimizePanel;
    private javax.swing.JPanel resetLevelP;
    private javax.swing.JPanel resetLevelP1;
    // End of variables declaration//GEN-END:variables
}
